### ISSUE TITLE
Table pg_class dosen`t exist

### ISSUE THREAD

**Issue by FernandoGambaro** [nicoribeiro/java_efactura_uy#3]
Hola nuevamente, veras que de a poco le estoy dedicando tiempo para programar y utilizar java_efactura_uy.
Luego de la corrección que hicisteis en la conexión a MySQL, logre iniciar el programa, y comencé a hacer pruebas con POSTMAN pero me da algunos errores.
Al enviar una consulta por POST, la ejecución del programa genera los siguientes errores

019-10-29 22:18:32,143 [error] from o.h.t.h.SchemaUpdate in application-akka.actor.default-dispatcher-4 - HHH000319: Could not get database metadata
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'java_efactura_uy.pg_class' doesn't exist
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
	at com.mysql.jdbc.Util.getInstance(Util.java:381)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1030)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3491)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3423)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1936)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2060)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2536)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2465)
	at com.mysql.jdbc.StatementImpl.executeQuery(StatementImpl.java:1383)
	at com.zaxxer.hikari.proxy.StatementProxy.executeQuery(StatementProxy.java:99)
	at com.zaxxer.hikari.proxy.StatementJavassistProxy.executeQuery(StatementJavassistProxy.java)

Supongo que no encuentra las tablas dentro de la base de datos, que le llame java_efactura_uy.
Tendrías el esquema de la DB?

Gracias nuevamente

**Comment by nicoribeiro** [comment]
Hola Fernando,

Buenísimo que le este metiendo mano. Por lo que veo la nomenclatura del nombre de la tabla es de postgres, raro, porque vos estas con mysql. Todas las tablas de la BBDD en postgres tienen el "pg_" como prefijo. No te flatará comentar alguna linea que tenga el driver de postgres? Ahora ando de vacaciones pero a mi regreso vicho tus archivos de config si queres.

saludos

**Comment by FernandoGambaro** [comment]
Buenas Nicolas, he revisado la configuración y está comentado lo que se indica esté y lo que no tiene que estar, no esta.
Lo que note que no ha creado las tablas dentro de la DB.

Lo vemos a tu regreso, buenas vacaciones.

**Comment by nicoribeiro** [comment]
Hola Fernando,

Estube probando en mi ambiente de pruebas y me salta el mismo error. Ya encontré la configuración que faltaba cambiar, era el dialecto de Hibernate (que se usa como ORM). De todas formas apareció un error luego de corregir esto especifico para Mysql (que no soporta secuencias en la BBDD) que debo atender. 

Te tengo al tanto.

**Comment by FernandoGambaro** [comment]
Gracias

**Comment by FernandoGambaro** [comment]
Buen día Nicolas, si me indicas por donde estaría la falla me gustaría darte una mano en buscar la solución. te parece?
Saludos
Fernando

**Comment by nicoribeiro** [comment]
Hola Fernando, gracias por ofrecerte. El tema esta solucionado, demore unos dias porque el cambio afectaba a produccion ya que cambia la forma en que hibernate usa las secuencias para las primary_keys de las tablas: attachment, email_message y respuesta. En el commit 60a47a5a8d4407bb2cc61712fbf965cf65782e52 estaria solucionado.

Saludos!
